.github/workflows/format.yml
plugins/accelerated-peft/tox.ini
plugins/framework/.pylintrc
plugins/framework/src/fms_acceleration/__init__.py
plugins/framework/src/fms_acceleration/cli.py
plugins/framework/src/fms_acceleration/framework.py
plugins/framework/src/fms_acceleration/framework_plugin.py
plugins/framework/src/fms_acceleration/utils/test_utils.py
plugins/framework/tests/test_framework.py
plugins/framework/tox.ini
scripts/benchmarks/benchmark.py

This PR does the following:
- Add linting, formatting and test as part of the github workflow
- Activate workflow matrix for `plugins/framework`
- Fix linting and formatting issues for `plugins/framework`
There should be a separate task to fix files for 
- `scripts/`
- `plugins/accelerated-peft`

Add GitHub Workflow for Linting , Formatting and Test. Activate Workflow for Framework

---

.github/workflows/format.yml
plugins/framework/pyproject.toml
scripts/benchmarks/README.md
scripts/benchmarks/benchmark.py
scripts/benchmarks/display_bench_results.py
scripts/generate_sample_configurations.py
scripts/run_benchmarks.sh
scripts/verify_generated_configurations.sh
tox.ini

From now on, all benchmarks need to run in `tox` environment for package version hygiene. 
```
tox -e run_benches
```
- note, since the PR is not yet merged we need to set `FHT_BRANCH=accel-pr`
In addition
- the `tox` command above accepts environment variables `DRY_RUN, NO_DATA_PROCESSING, NO_OVERWRITE`. See `scripts/run_benchmarks.sh`
-  in `run_benchmarks.sh` we will clear the `RESULT_DIR` if it exists, to avoid contaimination with old results. To protect against overwrite, then always run with `NO_OVERWRITE=true`.
- also the `run_benchmarks.sh` script will produce two CSVs now.  
* `raw_summary.csv`: this is the original one previously called `summary.csv`. This one will contain the raw results
* `benchmarks.csv`: this one is a processed version of `raw_summary.csv`. it only contains …

Improvements to Benchmark Scripts and Config Generation Workflow

---

plugins/accelerated-peft/configs/bnb.yaml
plugins/accelerated-peft/src/fms_acceleration_peft/framework_plugin_bnb.py
plugins/accelerated-peft/tests/test_peft_plugins.py
sample-configurations/CONTENTS.yaml
sample-configurations/baseline-peft-bnb-nf4-sample-configuration.yaml
scripts/benchmarks/scenarios.yaml
scripts/generate_sample_configurations.py

This PR addresses issue #10 by adding support for a FSDP-compatible HF QLoRA baseline to the our benchmarks. 
This will allow users to specify a `no_peft_model` field in the plugin config `bnb.yaml`. Specifying this field will bypass the `plugin.augmentation` function and allow SFTTrainer to manage the PEFT preparation of the model instead. 
- While the open-source approach to FSDP-compatible QLoRA removes the extraneous dtype casting in `prepare_model_for_kbit_training`, it only does so when the model is sharded. When on single device, it continues to use `prepare_model_for_kbit_training` and users will continue to experience a slowdown due to the extraneous casting.

Added support for running official HF baseline FSDP-QLoRA benchmark

---

.github/workflows/format.yml
plugins/accelerated-peft/configs/bnb.yaml
plugins/accelerated-peft/src/fms_acceleration_peft/autogptq_utils.py
plugins/accelerated-peft/src/fms_acceleration_peft/framework_plugin_autogptq.py
plugins/accelerated-peft/src/fms_acceleration_peft/framework_plugin_bnb.py
plugins/accelerated-peft/tests/test_peft_plugins.py
plugins/accelerated-peft/tox.ini
plugins/framework/.pylintrc
plugins/framework/pyproject.toml
plugins/framework/src/fms_acceleration/__init__.py
plugins/framework/src/fms_acceleration/cli.py
plugins/framework/src/fms_acceleration/framework.py
plugins/framework/src/fms_acceleration/framework_plugin.py
plugins/framework/src/fms_acceleration/utils/test_utils.py
plugins/framework/tests/test_framework.py
plugins/framework/tox.ini
sample-configurations/CONTENTS.yaml
sample-configurations/baseline-peft-bnb-nf4-sample-configuration.yaml
scripts/benchmarks/README.md
scripts/benchmarks/benchmark.py
scripts/benchmarks/display_bench_results.py
scripts/benchmarks/refs/a100_80gb.csv
scripts/benchmarks/scenarios.yaml
scripts/generate_sample_configurations.py
scripts/run_benchmarks.sh
scripts/verify_generated_configurations.sh
tox.ini

Upstreaming to main, see commit notes.

Upstream Main: Linting, Benchmarking, HF QLoRA baseline, FSDP fixes for GPTQ-LoRA

---

.github/workflows/format.yml
plugins/accelerated-peft/.pylintrc
plugins/accelerated-peft/src/fms_acceleration_peft/autogptq_utils.py
plugins/accelerated-peft/src/fms_acceleration_peft/framework_plugin_autogptq.py
plugins/accelerated-peft/src/fms_acceleration_peft/framework_plugin_bnb.py
plugins/accelerated-peft/tests/__init__.py
plugins/accelerated-peft/tests/test_peft_plugins.py
plugins/accelerated-peft/tox.ini

This PR addresses #9 with the following additions
- Completed Linting and Formatting of fms-acceleration-plugin with `10.00/10 ` rating
- Made changes to fms-acceleration-plugin `tox.ini` to support linting via tox
- Reactivated Linting and Formatting Workflow in Github Actions
Tested with sample experiments on accelerated-peft-bnb and accelerated-peft-autogptq to check for breakages
```
export CUDA_VISIBLE_DEVICES=0,1
accelerate launch \
--config_file scripts/benchmarks/accelerate.yaml \
--num_processes=2 \
--main_process_port=29500 -m tuning.sft_trainer \
--model_name_or_path mistralai/Mistral-7B-v0.1 \
--acceleration_framework_config_file sample-configurations/accelerated-peft-bnb-nf4-sample-configuration.yaml \
--packing True \
--max_seq_len 4096 \
--fp16 True \
--learning_rate 2e-4 \ …
```

Linting and Formatting for FMS-Acceleration-Peft package

---

plugins/accelerated-peft/src/fms_acceleration_peft/autogptq_utils.py
plugins/accelerated-peft/src/fms_acceleration_peft/framework_plugin_autogptq.py
scripts/benchmarks/README.md
scripts/benchmarks/benchmark.py

This PR addresses #18 with the following contributions
- Introduce  patch on AutoGPTQ's `make_sure_no_tensor_in_meta_device` to avoid raising an error when model has no bias in low memory mode
- Workaround to configuring `device_map` to `cpu` when loading checkpoints to avoid gpu memory consumption before trainer initialization.
_Note: This approach diverts consumption to cpu mem which could still bottleneck, a better approach could be to load it to `meta` device. QLoRA currently loads quantized models to `cpu` in low memory mode as well. See [here.](https://github.com/huggingface/transformers/pull/25107#issuecomment-2134833262)_
TODO:
- Actual device mapping to `meta` device
```
accelerate launch --config_file scripts/benchmarks/accelerate.yaml --num_processes=2 --main_process_port=29500 …
```

Workaround Low-Mem-Mode Patch for GPTQ-LoRA

---

plugins/fused-ops-and-kernels/src/fms_acceleration_foak/framework_plugin_fast_quantized_peft.py
plugins/fused-ops-and-kernels/src/fms_acceleration_foak/fused_ops/unsloth_lora/utils.py
scripts/benchmarks/refs/a100_80gb.csv

This PR addresses that when we use `lora_adapters_switch_ddp_from_fsdp` to ignore the lora modules, we have previously also ignored the base layers
- this will cause a big memory increment since base layer can be very large
This fix properly addresses it, by ignoring only the LoRA modules
- for `auto_gptq` we found that it works well
- for `bnb`, this will cause the `quant_state` on the parameter to be destroyed, to address this, we now get the `quant_state` from the base_layer, thus also addressing https://github.com/foundation-model-stack/fms-acceleration/issues/3
**Before Fix: No Sharding of Attention Base Layer**
| Model Name |  Framework<br>Config  |  No. GPU  |  Per Dev. Batch Size  |  Throughput<br>per<br>device<br>(toks/sec)  |  Torch<br>Memory<br>Allocated (GiB)  | …

Address Incorrect Ignoring of Base Layer Modules for FSDP with Kernels

---

scripts/benchmarks/benchmark.py

This PR shifts all GPU memory computation from the end of each experiment to the end of the benchmarking script. This avoids the need to rerun experiments, instead the raw values are saved and the aggregated values are computed at the end across all the experiments in `gather_report`.

Shift GPU Memory Computation to End of Benchmarking Script

---

README.md
plugins/framework/src/fms_acceleration/constants.py
plugins/framework/src/fms_acceleration/framework.py
scripts/benchmarks/benchmark.py
scripts/benchmarks/display_bench_results.py
tox.ini

Since we had changed the integration in `fms-hf-tuning` via dataclasses, this PR fixes the benches but allowing the configuration YAML to be pointed to by an environment variable

Allow Benchmarks to be run with configuration pointed to in YAML env variable

---

plugins/accelerated-peft/requirements.txt
plugins/framework/pyproject.toml
plugins/framework/tests/__init__.py
tox.ini

Bounding package versions to avoid recent incompatibilities for
- AutoGPTQ (Building from latest commit require HPC libraries as dependencies)
- numpy (recently updated to `2.0`, this isnt compatible for torch versions `<2.3`)

Bound Package Versions

---

README.md
plugins/accelerated-peft/requirements.txt
plugins/framework/pyproject.toml
plugins/framework/src/fms_acceleration/constants.py
plugins/framework/src/fms_acceleration/framework.py
plugins/framework/tests/__init__.py
plugins/fused-ops-and-kernels/README.md
plugins/fused-ops-and-kernels/src/fms_acceleration_foak/fused_ops/unsloth_lora/bnb/fast_lora.py
plugins/fused-ops-and-kernels/src/fms_acceleration_foak/fused_ops/unsloth_lora/gptq/fast_lora.py
plugins/fused-ops-and-kernels/src/fms_acceleration_foak/fused_ops/unsloth_lora/utils.py
plugins/fused-ops-and-kernels/tests/test_fused_ops.py
plugins/fused-ops-and-kernels/tox.ini
scripts/benchmarks/benchmark.py
scripts/benchmarks/display_bench_results.py
scripts/benchmarks/scenarios.yaml
tox.ini

- clamp package versions (temporary) #36, #42 
- add lora dropout to fused ops 
- add YAML to be configured by envar #40

Upstream Main: Add Lora Dropout, YAML EnvVar Configuration

---

plugins/accelerated-peft/tox.ini
plugins/framework/src/fms_acceleration/cli.py
plugins/fused-ops-and-kernels/tox.ini

This PR prepares the accelerated-peft and fused-ops-and-kernels plugins for publishing.
Items:
- Change Framework CLI tool to support installation from PyPi
- Set version numbers for both plugin package
- Enable tox build sections for both plugins

Publish Accelerated Peft and Fused-Ops Plugins

---

plugins/accelerated-peft/README.md
plugins/accelerated-peft/configs/autogptq.yaml
plugins/accelerated-peft/pyproject.toml
plugins/accelerated-peft/requirements.txt
plugins/accelerated-peft/src/fms_acceleration_peft/framework_plugin_autogptq.py
plugins/accelerated-peft/tests/test_gptqmodel.py
plugins/accelerated-peft/tests/test_peft_plugins.py
plugins/accelerated-peft/tox.ini
plugins/framework/src/fms_acceleration/framework_plugin.py
sample-configurations/accelerated-peft-autogptq-foak-sample-configuration.yaml
sample-configurations/accelerated-peft-autogptq-sample-configuration.yaml

This PR applies additional fixes to #48,
- removed direct dependency in plugin
- edited plugin README with information to install direct dependencies when creating a legacy GPTQ-LORA
- Shifted `use_external_lib` argument from plugin argument to configuration object field
- Added additional unit tests to ensure 
- the new field is read
- the correct package is imported
- appropriate errors are thrown
- regenerated sample configuration yamls to include the new field
```
============================================================================================================================================================================================================ test session starts ====================================================================================================== …
```

Local autogptq fix

---

plugins/framework/pyproject.toml
plugins/fused-ops-and-kernels/src/fms_acceleration_foak/kernels/unsloth/cross_entropy_loss.py
plugins/fused-ops-and-kernels/src/fms_acceleration_foak/kernels/unsloth/rope_embedding.py
scripts/benchmarks/benchmark.py
scripts/benchmarks/compare_with_reference.py
scripts/run_benchmarks.sh
tox.ini

This PR:
- fix some robustness issues in `run-benchmarks.sh`. In particular, note that the empty scenario filter is now `"none"`.
- This releases transformers to `4.43.3`
- Below shows the results for `7B`
| ![image](https://github.com/user-attachments/assets/efe04bf4-f7da-4065-82ab-edad60cc528e) | ![image](https://github.com/user-attachments/assets/7502e03e-305e-4d93-ae6a-92a78f59087b) |
--|--
--|--
| ![image](https://github.com/user-attachments/assets/de213ca5-2da3-4ce8-967c-84e9da1f8b1e) |  ![image](https://github.com/user-attachments/assets/025bb997-6436-4dfb-bcce-06107249e28e) |

Address Package Bound and Triton Issues for Torch 2.4

---

plugins/instruct-lab/src/fms_acceleration_ilab/flash_attn.py
plugins/instruct-lab/src/fms_acceleration_ilab/framework_plugin_padding_free.py
plugins/instruct-lab/src/fms_acceleration_ilab/ilab_utils.py

The PR #57 had a couple of mistakes that needed to be fix,  This is because of two things
1. the `flash_attention_forward` was moved out earlier
2. the actual padding free fix was done later, and is still not yet relaased (probably 4.44)
The strategy now is simple:
- if we can import DataCollatorWithFlattening successfully, means the padding free fix is done
- if we can import `_flash_attention_forward`, means the function has been seperated out
**Augmentation**
1. If padding free fix is done, then nothing to do, otherwise some patching is required
2. Patch the static or method `_flash_attention_forward` depending on version.
Some redesign is done, since `_flash_attention_forward` couild either be a method or function, then thje previous method to bind `_flash_attention_forward` by …

Fix Mistakes with FA Padding Free

---

plugins/instruct-lab/src/fms_acceleration_ilab/framework_plugin_padding_free.py

This PR fixes a missing dataloader preparation call in the PaddingFree Plugin that will cause num optimization steps in distributed experiments to be computed wrongly. 
With this fix, the relative performance improvement between `padded` vs `padding-free` approximately matches for 
-  FMS-Acceleration PaddingFree plugin, 24%
-  Natively supported padding free in Transformers, 26%
| Model | DataProcess | Grad Accum | Per Device Batch Size | Num Devices | Time | Throughput (token/s) / device |
| -------- | ------- | ------- | ------- | ------- | ------- | ------- |
| Mistral-7B | Transformers Padded | 2 | 4 | 8 | 812 | 1216 |
| Mistral-7B | Transformers Native PaddingFree | 2 | 4 | 8 | 596 | 1658 |
| Model | DataProcess | Grad Accum | Per Device Batch Size | Num Devices | Time | Throughput …

Rectify Missing Dataloader Preparation Call in PaddingFree Plugin Method

---

scripts/benchmarks/benchmark.py
scripts/benchmarks/data_processing.py

NOTE: this PR regards only data preparation for benches. It does not affect any plugin operation
- this only regards the flow where `chat_templates` are specified along with `tokenize: True`
When using chat templates, using response templates are error prone and trouble some, and it forces us to insert extranous
markers into the templates just for the sake of loss masking
For example below we add a `RESPONSE:` just to delineate the `prompt` from the `response`
```yaml
chat_template: |
{%- for message in messages %}
{{ message['prompt'] }} RESPONSE: {{ message ['response'] }}
{%- endfor %}
tokenize: True
```
This PR allows us to do the following via the new `response_field` specification:
```yaml
chat_template: |
{%- for message in messages %}
{{ message['prompt'] }}
{%- endfor %} …
```

Benchmarking: Add Response Field to Use Chat Templates Without Response Template

---

.github/workflows/format.yml
plugins/accelerated-peft/src/fms_acceleration_peft/autogptq_utils.py
plugins/accelerated-peft/src/fms_acceleration_peft/framework_plugin_autogptq.py
plugins/accelerated-peft/tests/test_gptqmodel.py
plugins/accelerated-peft/tests/test_peft_plugins.py
plugins/accelerated-peft/tests/test_q4_triton.py
plugins/accelerated-peft/tests/test_triton.py
plugins/attention-and-distributed-packing/README.md
plugins/fused-ops-and-kernels/src/fms_acceleration_foak/framework_plugin_fast_quantized_peft.py
plugins/fused-ops-and-kernels/src/fms_acceleration_foak/models/llama.py
plugins/fused-ops-and-kernels/src/fms_acceleration_foak/models/mistral.py
plugins/fused-ops-and-kernels/src/fms_acceleration_foak/models/mixtral.py
plugins/fused-ops-and-kernels/src/fms_acceleration_foak/models/utils.py
plugins/fused-ops-and-kernels/tests/test_fused_ops.py

This PR formats the code and fixes the format workflow to fail if additional formatting is required in GH Actions

Fix formatter

---

plugins/accelerated-peft/src/fms_acceleration_peft/autogptq_utils.py
plugins/accelerated-peft/src/fms_acceleration_peft/framework_plugin_autogptq.py
plugins/accelerated-peft/src/fms_acceleration_peft/gptqmodel/utils/peft.py

This is a fix for the gptq-peft plugin to follow the official peft implementation where specifying `target_modules='all-linear'` will install adapters on all linear layers. Note that [HF by default](https://github.com/huggingface/peft/blob/95b39642fb7e627464c81011c8c20d4676798cc9/src/peft/tuners/tuners_utils.py#L990) will not install adapters on `lm_head` for `all-linear`. This applies to both our locally maintained `gptqmodel` as well as the opensource `auto_gptq`.
- Run with adapters installed on all linear modules `--target_modules 'all-linear`
```
python -m tuning.sft_trainer --model_name_or_path TheBloke/Mistral-7B-v0.1-GPTQ --packing False --max_seq_len 4096 --auto_gptq triton_v2 True --training_data_path orca/benchmark_outputs/data/cache_TheBloke_Mistral_7B_v0.1_GPTQ.json …
```

fixed bug in peft installation for gptqmodel

---

plugins/accelerated-peft/pyproject.toml
plugins/accelerated-peft/src/fms_acceleration_peft/autogptq_utils.py

This is a fix to address a mistake with a check on `target_modules` in peft_config. Target modules come in as a `set` and the assertion will be raised unnecessarily.
**mistake:**
`assert isinstance(tm, (list, str)), "target modules can only be list or string"`
**correction:**
`assert isinstance(tm, (list, set, str)), "target modules can only be list, set or string"`
Tested with alpaca on both `all-linear` and `q_proj k_proj v_proj o_proj`
`all-linear`
```
***** Running training *****
Num examples = 2,754
Num Epochs = 1
Instantaneous batch size per device = 4
Total train batch size (w. parallel, distributed & accumulation) = 4
Gradient Accumulation steps = 1
Total optimization steps = 100
Number of trainable parameters = 41,943,040
```
`q_proj k_proj v_proj o_proj`
```
***** Running …
```

Fix Bug on Peft Config Check in AutoGPTQ Plugin

---

plugins/accelerated-peft/requirements.txt
plugins/accelerated-peft/src/fms_acceleration_peft/framework_plugin_bnb.py
plugins/fused-ops-and-kernels/README.md
plugins/fused-ops-and-kernels/configs/fast_quantized_peft.yaml
plugins/fused-ops-and-kernels/src/fms_acceleration_foak/fused_ops/unsloth_lora/bnb/fast_lora.py
plugins/fused-ops-and-kernels/src/fms_acceleration_foak/fused_ops/unsloth_lora/gptq/fast_lora.py
plugins/fused-ops-and-kernels/src/fms_acceleration_foak/fused_ops/unsloth_lora/utils.py
plugins/fused-ops-and-kernels/tests/test_foak_plugins.py
sample-configurations/accelerated-peft-autogptq-foak-padding-free-sample-configuration.yaml
sample-configurations/accelerated-peft-autogptq-foak-sample-configuration.yaml
sample-configurations/accelerated-peft-bnb-nf4-foak-padding-free-sample-configuration.yaml
sample-configurations/accelerated-peft-bnb-nf4-foak-sample-configuration.yaml
sample-configurations/foak-fast-kernels-sample-configuration.yaml
scripts/benchmarks/benchmark.py
scripts/benchmarks/refs/a100_80gb_granite.csv
scripts/benchmarks/refs/requirements_granite.txt
scripts/benchmarks/scenarios-granite.yaml
scripts/benchmarks/scenarios.yaml
scripts/generate_sample_configurations.py
scripts/run_benchmarks.sh

In this PR we update the benchmarks for `GraniteCausalLM`
- in addition, the [README.md](https://github.com/foundation-model-stack/fms-acceleration/blob/granite-foak/plugins/fused-ops-and-kernels/README.md#adding-support-for-a-new-model)  is also updated to describe how a new model can be added in the future
- NOTE: we did not update the GPTQ results in the bench. will do this possibly at a later time.
Note this PR requires the following dependency updates
- `transformers>=4.45`: for `GraniteCausalLM`
- `accelerate>=0.34.1`:  required for `transformers>=4.45` if `GraniteCausalLM` is needed.
- `trl > 0.11.1`: when using baseline bnb, requires this fix for a bug that was introduced in `transformers==4.45` https://github.com/huggingface/trl/pull/2089
- `bitsandtbyes==0.43.3`: it seems that …

Update Benchmarks and Documentation for GraniteCausalLM

---

plugins/accelerated-peft/src/fms_acceleration_peft/autogptq_utils.py
plugins/accelerated-peft/src/fms_acceleration_peft/framework_plugin_autogptq.py
plugins/accelerated-peft/src/fms_acceleration_peft/framework_plugin_bnb.py
plugins/accelerated-peft/src/fms_acceleration_peft/gptqmodel/models/base.py
scripts/benchmarks/scenarios-granite.yaml
scripts/benchmarks/scenarios.yaml

This PR provides two fixes
1. fallback to target module defaults. To keep in line with regular HF behavior, we fallback to HF default target modules if `--target_modules` happen to be omitted from the `peft_config`
2. disabling the gptq v1 to v2 conversion: we revert back to default HF behavior and disable offloading. Upon reviewing the [accelerate.load_checkpoint_in_model](https://github.com/huggingface/accelerate/blob/127818fc27ebe5cb236357fff59ff1748326d643/src/accelerate/utils/modeling.py#L1611) i know start to feel the offloading may not be needed moving forward. The main purpose of that function is to read the (sharded) checkpoint and load it into the model (on the CPU, since low_cpu_mem_mode is not working for GPTQ). I think the proper way forward is to get `low_cpu_mem_mode` …

Fixes to Accelerated Peft

---

plugins/accelerated-peft/README.md
plugins/accelerated-peft/src/fms_acceleration_peft/framework_plugin_bnb.py
plugins/fused-ops-and-kernels/README.md
plugins/fused-ops-and-kernels/src/fms_acceleration_foak/framework_plugin_fast_kernels.py
plugins/fused-ops-and-kernels/src/fms_acceleration_foak/fused_ops/unsloth_lora/bnb/fast_lora.py
plugins/fused-ops-and-kernels/src/fms_acceleration_foak/fused_ops/unsloth_lora/gptq/fast_lora.py
scripts/benchmarks/accelerate.yaml
scripts/benchmarks/compare_with_reference.py
scripts/benchmarks/display_bench_results.py
scripts/benchmarks/refs/a100_80gb.csv
scripts/benchmarks/refs/requirements.txt
scripts/benchmarks/scenarios.yaml

This PR fixes:
- make `accelerate.yaml` compatible with v1
- fixed error introduced during #86 when generalizing LoRA fusedOps for Granite (that has biases).
- relaxed the datatypes, allow Full-FT-FOAK and  PEFT-FOAK  to run in native (i.e. not mixed) precision.
- update full-ft FOAK benches that were not updated in #79. Updated mixed precision settings in bench to match the state of benches before #79.
We have removed mixed precision for these benches and restored performance, see
[outliers.csv](https://github.com/user-attachments/files/17356032/outliers.1.csv)
**Compatibility Matrix with Mixed Precision**
torch_dtype | Mixed Precision | Full-FT-FOAK | PEFT-FOAK | QPEFT-FOAK
-- | -- | -- | -- | --
FLOAT16 | - | **Compatible**  | **Compatible** | ✗
FLOAT16 | FP16 | ValueError: …

Quickfix: Accelerate YAML and LoRA Fused Ops

---

plugins/accelerated-peft/src/fms_acceleration_peft/framework_plugin_autogptq.py

In the previous PR #90 we applied a fix for retying the weights, however it was incorrectly done for AutoGPTQ. 
- for BNB, we apply the fix only for certain transformers and trl versions, because the `meta` device `low_cpu_mem_mode` was enabled only for those versions
- however for GPTQ, this is not the case, since we handle `low_cpu_mem_mode` seperately from HF. Hence the fix must be applied immediately. This PR fixes that.

Apply Retie Weights Fix Regardless of Transformers and TRL version for AutoGPTQ

---

plugins/accelerated-peft/src/fms_acceleration_peft/framework_plugin_autogptq.py
plugins/accelerated-peft/src/fms_acceleration_peft/framework_plugin_bnb.py
plugins/accelerated-peft/src/fms_acceleration_peft/fsdp_utils.py
plugins/fused-ops-and-kernels/src/fms_acceleration_foak/framework_plugin_fast_quantized_peft.py

Due to the recent Low CPU Memory Fixes #90 that happened for `transformers >= 0.45`, this is a remaining issue. 
If the parameters are in the `meta` device, then they will not be able to be resized. This will cause a problem in `fms-hf-tuning`, where the embedding table is resized based on the number of new tokens.
This PR is a fix to move selected parameters into the CPU device; this is caused by the incosistentcy of the fix in https://github.com/huggingface/transformers/pull/33154 for the QLoRA and non-quantized cases, see below. We adopt a solution that is in between.
- for QLoRA, all parameters are left on the `meta` device
- for full finetuning, the parameters are initialised using `empty` and moved to the `cpu` device.
The former is the correct logic, but it will cause problems when …

Fix Issue with Resizing Parameters on the Meta Device in Low CPU Mem Mode

---

plugins/fused-ops-and-kernels/src/fms_acceleration_foak/framework_plugin_fast_quantized_peft.py
plugins/fused-ops-and-kernels/src/fms_acceleration_foak/fused_ops/unsloth_lora/bnb/fast_lora.py
plugins/fused-ops-and-kernels/src/fms_acceleration_foak/fused_ops/unsloth_lora/gptq/fast_lora.py
plugins/fused-ops-and-kernels/src/fms_acceleration_foak/fused_ops/unsloth_lora/utils.py
plugins/fused-ops-and-kernels/tests/test_fused_ops.py

This PR fixes #97. 
- update `bnb` and `auto_gptq` fused-lora to correctly account for dropout in the backward.
- fix tests to correct patch model, and compute and test input gradients for `test_adapter_gradients_match_with_attention_layer`
- unfortunately we cannot test `input_grads` for GPTQ in `test_adapter_gradients_match_with_attention_layer`, this is a limitation of unable to properly load a small GPTQ model.
~In addition we also disable the MLP fused op for certain models, and removed the old `fast_quantized_peft` plugin.~ We defer this to another PR
Looks quite good. The node I got is a little slower, but everything seems to be inline.
--|--
[benchmarks.csv](https://github.com/user-attachments/files/17671833/benchmarks.csv)

Fix Dropout in Fused LoRA Operations

---

plugins/accelerated-peft/src/fms_acceleration_peft/gptqmodel/nn_modules/triton_utils/dequant.py
plugins/fused-ops-and-kernels/src/fms_acceleration_foak/framework_plugin_fast_kernels.py
plugins/fused-ops-and-kernels/src/fms_acceleration_foak/fused_ops/unsloth_lora/bnb/fast_lora.py
plugins/fused-ops-and-kernels/src/fms_acceleration_foak/fused_ops/unsloth_lora/gptq/fast_lora.py

This PR fixes issue: https://github.com/foundation-model-stack/fms-acceleration/issues/107
Changes:
Modified the autocasting decorator to `@torch.amp.custom_fwd and @torch.amp.custom_bwd` for autograd function.

fix: Deprecation Warnings in AutoCast API

---

plugins/accelerated-moe/src/fms_acceleration_moe/utils/checkpoint_utils.py

Saving sharded safetensors from this [comment](https://github.com/foundation-model-stack/fms-acceleration/pull/114#issuecomment-2529945526) to complete PR #114
Checkpoint utils saving before sharded savetensors:
Checkpoint utils saving after sharded savetensors:
Model in: `/testing/tuning/output/granite-3b-moe/ft/20241121_1315-tone-FAST/`

feat: save sharded safetensors

---

plugins/accelerated-moe/src/fms_acceleration_moe/utils/checkpoint_utils.py

#114 for reference, with linting

feat: Checkpoint utils safetensors

---

plugins/fused-ops-and-kernels/src/fms_acceleration_foak/framework_plugin_fast_kernels.py
plugins/fused-ops-and-kernels/src/fms_acceleration_foak/models/granite.py
plugins/fused-ops-and-kernels/src/fms_acceleration_foak/models/llama.py
plugins/fused-ops-and-kernels/src/fms_acceleration_foak/models/mistral.py
plugins/fused-ops-and-kernels/src/fms_acceleration_foak/models/utils.py
plugins/fused-ops-and-kernels/src/fms_acceleration_foak/utils.py
plugins/fused-ops-and-kernels/tests/test_model_utils.py

Unwittingly due to the recent PR #106 we had introduced a `filter_mp_rules` function and placed it into `models.utils`. Unfortunately, that file does cuda kernel imports, and will cause `pip install ` failures in machines with no GPU. This is is critical because it precludes building images in CI machines that typically do not have GPUs.
<details>
<summary> Failure </summary>
#33 15.79   File "/usr/lib64/python3.11/ctypes/__init__.py", line 394, in __getitem__
#33 15.79     func = self._FuncPtr((name_or_ordinal, self))
#33 15.79            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#33 15.79 AttributeError: /home/tuning/.local/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cdequantize_blockwise_fp32
..#33 ERROR: process "/bin/sh -c if [[ …

Decouple Filter MP Rules function from cuda imports

---

plugins/accelerated-peft/src/fms_acceleration_peft/framework_plugin_autogptq.py
plugins/accelerated-peft/src/fms_acceleration_peft/framework_plugin_bnb.py
plugins/accelerated-peft/tests/test_peft_plugins.py
plugins/attention-and-distributed-packing/src/fms_acceleration_aadp/framework_plugin_multipack.py
plugins/attention-and-distributed-packing/src/fms_acceleration_aadp/framework_plugin_padding_free.py
plugins/framework/README.md
plugins/framework/src/fms_acceleration/framework.py
plugins/framework/src/fms_acceleration/framework_plugin.py
plugins/framework/src/fms_acceleration/utils/test_utils.py
plugins/framework/tests/test_framework.py
plugins/fused-ops-and-kernels/src/fms_acceleration_foak/framework_plugin_fast_kernels.py
plugins/fused-ops-and-kernels/tests/test_foak_plugins.py

Nit fix for function name. Would require a change in `sft_trainer.py` as well if this is wanted.

fix: function name 'requires_agumentation' to 'requires_augmentation'

---

plugins/accelerated-moe/src/fms_acceleration_moe/framework_plugin_scattermoe.py

**Description**
Step 1 of 3 for enabling LoRA on ScatterMoE: move model loader functionality to augmentation. This makes it so the plugin doesn't have to be standalone as well. 
**Testing**
Testing on fms-hf-tuning with augmentation function instead of model loader shows similar results to [#390](https://github.com/foundation-model-stack/fms-hf-tuning/pull/390):
```
{
"model_name_or_path": "/ibm_dmf_lakehouse/models/base_training/shared/granite-3.0-3b-a800m-base/r240924a",
"training_data_path": "/testing/tuning/input/cc_tone_sft_format_1000_train.json",
"output_dir": "/testing/tuning/output/granite-3b-moe/ft/20240107_1014-tone-FAST",
"save_model_dir": "/testing/tuning/output/granite-3b-moe/ft/20240107_1014-tone-FAST/save_model",
"num_train_epochs": 10.0,
"per_device_train_batch_size": 2, …
```

feat: move model loader functionality to augmentation

---

plugins/accelerated-moe/src/fms_acceleration_moe/framework_plugin_scattermoe.py

Current implementation uses global rank of the process to prepare the device index which would not work in a multi node setting. Therefore, we would need to use local rank since devices are not continuously indexed across the nodes.

fix: Allow for multi node training for accelerated moe

---

plugins/accelerated-moe/src/fms_acceleration_moe/utils/__init__.py
plugins/accelerated-moe/src/fms_acceleration_moe/utils/checkpoint_utils.py

Add a wrapper function to wrap complete dcp to safetensor logic in order to enable easy downstream usage through this function without needing to redundantly repeat the same set of steps.

chore: Move dcp to safetensors to a wrapper function for downstream usage

---

plugins/accelerated-moe/.pylintrc
plugins/accelerated-moe/src/fms_acceleration_moe/framework_plugin_scattermoe.py
plugins/accelerated-moe/src/fms_acceleration_moe/utils/checkpoint_utils.py
plugins/accelerated-moe/src/fms_acceleration_moe/utils/scattermoe.py
plugins/accelerated-moe/src/fms_acceleration_moe/utils/scattermoe_prepare.py

Limited version of #139 without support for router or expert layers

feat: lora for accelerated MoE - limited

---

plugins/accelerated-peft/src/fms_acceleration_peft/gptqmodel/models/base.py

`dtype_byte_size` is no more supported in transformers due to its inaccuracies - https://github.com/huggingface/transformers/pull/37144 and related issues.
We should move to torch native solution `element_size()`.

fix: use element_size

---

plugins/accelerated-moe/src/fms_acceleration_moe/utils/checkpoint_utils.py
plugins/accelerated-moe/tox.ini

Goes with [#545](https://github.com/foundation-model-stack/fms-hf-tuning/pull/545) to allow all-linear for ScatterMoE. This PRs always filters out the `router` in the LoRA state dict, which should be reversed when expert tuning support for LoRA layers is added in, and has been noted as such. This will allow users to pass `all-linear` as target modules when using ScatterMoE

fix: filter out router so `all-linear` can be tuned for LoRA target modules

---

plugins/fused-ops-and-kernels/src/fms_acceleration_foak/kernels/unsloth/cross_entropy_loss.py
plugins/fused-ops-and-kernels/src/fms_acceleration_foak/kernels/unsloth/rope_embedding.py

update datatype to int.
[reference 1](https://github.com/unslothai/unsloth/blob/3808d801a766b67f23bb1727c13da417fcadbdf8/unsloth/kernels/rope_embedding.py#L36)
[reference 2](https://github.com/unslothai/unsloth/blob/3808d801a766b67f23bb1727c13da417fcadbdf8/unsloth/kernels/cross_entropy_loss.py#L290)
Following is screenshot of the run after the fix:
This fix is extension to #148

fix: update datatype to int
